### PR TITLE
Work on the initial version of the microservice template.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Since we're using a microservice architecture, we're going to need a template that we can easily use to jump right in on the application and feature logic without having to worry about all of the operations & systems stuff.

In particular, the template should provide the following:

## Django settings for REST.

To keep things simple, we want non-user-facing microservices to talk to each other without the overhead of authentication. That means these microservices will have to be deployed under the protection of a private network, and we'll need a API gateway microservice before we go live that handles authentication for external user requests on its own.

* Dev: Same as prod.
* Stage: Same as prod.
* Prod: Serve all requests for all endpoints without auth, no throttling, and page numbers for pagination with a page size of 30.

## Django settings for media files.

All media files need to go to external storage, i.e. AWS S3 or OpenStack SWIFT.

I really like the high availability provided by S3, and we're probably not going to be using an immense amount of it, so send all non-dev media files there.

Note that this doesn't take into account any super special security considerations, i.e. separate buckets for different users, etc. -- all media files for all users will just go in a single bucket, with access only given to our internal services, which'll pass on individual files to the client at the front-end.

But in case that security is needed in the future, we'll need a way to tell files apart in a scalable way, so for now when our application logic uploads media files, prepend the user's UUID to the file.

* Dev: File uploads go to local disk, i.e. a media/ folder.
* Stage: File uploads go to a _stage_ S3 bucket with the name of the microservice and some appended identifier like a UUID.
* Prod: File uploads go to a _prod_ S3 bucket with the name of the microservice and some appended identifier like a UUID.

## Django settings for log collection.

Since we're going with containers, and many microservices will be stateless, we don't want to hold logs onto a local disk, even if we plan on forwarding them somewhere eventually, and instead send them directly from the get-go to a central store.

* Dev: configure Django to send logs to the developer's console. 
* Stage: configure Django to send logs to a central _stage_ Logstash server.
* Prod: configure Django to send logs to a central _prod_ Logstash server.

## Django settings for highly available (HA) databases.

Since HA databases come in many shapes and sizes, and each microservice may have a slightly different requirement, just configure Django to send writes and reads to separate hosts by default for all environments, and we can handle what host that really is on the deployment side.

The engine should be MySQL.

* Dev: The default read and write hosts should be to a local MySQL container, i.e. a single database.
* Stage: The default read and write host should be equal to the _stage_ load balancer / service for database read-only and write-only operations, respectively.
* Prod: The default read and write host should be equal to the _prod_ load balancer / service for database read-only and write-only operations, respectively.

## Django settings for broker & cache.

Microservices will use Celery for long-running background tasks, and will use Redis as the broker for those tasks. Additionally, caching can be kept simple by also being handled by Redis, since it can cover both use cases.

Note: Redis itself should be HA with sentinels, with different deployments per microservice (just reuse the same Kubernetes manifests).

* Dev: The default broker and cache should be Redis in a local container.
* Stage: The default broker and cache should be _stage_ Redis.
* Prod: The default broker and cache should be _prod_ Redis.

## Django settings for email.

Right now the outgoing mail server for jira.mslm.me is hosted by AWS SES, so we can reuse this service for our microservice's outgoing mail servers.

* Dev: send email to the developer's console.
* Stage: same as _prod_.
* Prod: send email to actual recipients through AWS SES.

### CODE REVIEW

**Comment by calvinqh** [comment]
When I tried to setup the repo with cookiecutter I ran into a problem with the pip install part of the post hook. It failed when trying to install mysqlclient. Solved this my installing libgda-mysql (Im using arch linux distro).

Another thing is when I run fab manage:runserver I get the following warning.

```
/usr/local/lib/python3.6/site-packages/environ/environ.py:624: UserWarning: Error reading /open-matrimony/app/app/.env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
/usr/local/lib/python3.6/site-packages/environ/environ.py:624: UserWarning: Error reading /open-matrimony/app/app/.env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
```

But it didn't seem to affect anything. Everything runs perfectly!

**Comment by UmanShahzad** [comment]
@calvinqh Nice, thanks for running this!

For the MySQL lib, when we create Ansible playbooks to install our microservices, we'll have them download the appropriate package for the distro. But that's good to know about this affecting devs -- I may add a command in the post-hook to download the appropriate package, but it may be difficult because I'd have to change the name per-distro. I'll see what I can do.

The warning is harmless, yep, it's because we aren't actually using a `.env` file. However if you wanted to modify some of the default Django developer settings for any reason, you'd do it through a `.env` file (ignored by `.gitignore`), which'll then get loaded and the warning won't show anymore.

Btw, you used `fab manage:runserver`, but was that needed? The container should run a `wsgi` server automatically upon startup, which you can access at `localhost:1786`.

**Comment by calvinqh** [comment]
Just tried accessing accessing localhost:1786 without running runserver. It works fine!

**Comment by UmanShahzad** [comment]
Thanks @calvinqh :)

**Pull request merged**
